dependencies:
  '@rush-temp/packagea': 'file:projects/packagea.tgz'
  '@rush-temp/packageb': 'file:projects/packageb.tgz'
  lodash: 4.17.11
packages:
  /lodash/4.17.11:
    dev: false
    resolution:
      integrity: sha512-cQKh8igo5QUhZ7lg38DYWAxMvjSAKG0A8wGSVimP07SIUEK2UO+arSRKbRZWtelMtN5V0Hkwh5ryOto/SshYIg==
  'file:projects/packagea.tgz':
    dependencies:
      lodash: 4.17.11
    dev: false
    name: '@rush-temp/packagea'
    resolution:
      integrity: sha512-wnWufY1i+IeIPf3ncC8e2Jj7hts9QSJZCEDCYhaIlE53oesdY8wnHzyj4ln4XHqJw5KvDL3Aca1jcE9Go1fdmQ==
      tarball: 'file:projects/packagea.tgz'
    version: 0.0.0
  'file:projects/packageb.tgz':
    dev: false
    name: '@rush-temp/packageb'
    resolution:
      integrity: sha512-j6jwdqBXXtmnb2sg4DDemmG1kUpTcaigiMqJJ+QEz791FSws8s0k8aMWt8xYuP9qNZUQAQJtXH+Ww/tusgsIVw==
      tarball: 'file:projects/packageb.tgz'
    version: 0.0.0
registry: 'https://registry.npmjs.org/'
shrinkwrapMinorVersion: 9
shrinkwrapVersion: 3
specifiers:
  '@rush-temp/packagea': 'file:./projects/packagea.tgz'
  '@rush-temp/packageb': 'file:./projects/packageb.tgz'
  lodash: 4.17.11
