storage: ./storage
# auth:
#   htpasswd:
#     file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@example/*':
    access: $all
    publish: $all
    proxy: npmjs
  '**':
    proxy: npmjs
logs:
  - { type: stdout, format: pretty, level: http }
